# Site settings
title: Alexandr Savinov - Data Commander
author: Alexandr Savinov

twitter_username: asavinov
github_username:  asavinov

url: http://conceptoriented.org

# Build settings
theme: jekyll-theme-slate
#show_downloads: true
#highlighter: rouge

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"

# conceptoriented.org Google Analytics
google_analytics: UA-43712358-2

plugins:
  - jekyll-redirect-from
